### ISSUE TITLE
First impression

### ISSUE THREAD

**Issue by marcelhollerbach** [coolcrowd/control-ui#1]
- cool thing
- in the experiment view the prieces are shown as "10" even if you have selected 0.10 in the wizard.
- Can we have a $ sign at the prieces ?
- The input of the constraints is not then easy to understand that you just write sentences in new lines ...
- Can you refresh the view if s.o. hitted publish ?

**Comment by kelunik** [comment]
`$` or better `US cents` is a good idea. It shouldn't be possible to input `0.10` into the field. Just a new help sentence for constraints solves it?

**Comment by marcelhollerbach** [comment]
I am not talking about inputting 0.10 into the field I am talking about the experiment showing 10 instead of 0.10.
Isnt there a way to get them automatically into bullet enumeration ?

**Comment by kelunik** [comment]
I think displaying it in `cents` is fine, since we'll have small values almost always?

There's always a way, it's just more or less complicated.

**Comment by marcelhollerbach** [comment]
Then make it in the wizards also cents and not 0.10 (looks like this is inconsistent text says cents)

**Comment by kelunik** [comment]
Did you input `0.10` and it worked? Should always be cents in the wizard.

**Comment by marcelhollerbach** [comment]
cannot test right now, something is bugging again.
