### ISSUE TITLE
Show if answers violated constraints

### ISSUE THREAD

**Issue by lckr** [coolcrowd/control-ui#18]
The answer overview of an experiment should show if an answer violated a constraint.
This can be done comparable to showing the feedback of a rater. We could autogenerate a feedback if there is none given

**Comment by kelunik** [comment]
I think showing all is too much. We need to filter them somehow, otherwise a single violation will show them, even if 9 other people rated differently, see https://crowdcontrol.ipd.kit.edu/experiments/3/answers
