### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/control-ui#6]
a working docker image would be nice

**Comment by kelunik** [comment]
Why?

**Comment by LeanderK** [comment]
to integrate with the docker-compose file in the object-service

**Comment by LeanderK** [comment]
since the worker-ui got its dockerfile this is the last one not integrated, so it would be cool if you could fix the image.

**Comment by marcelhollerbach** [comment]
Can you get this in the next days ? Would make testing/working much easier.
