### ISSUE TITLE
Support for Platform Modes

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/control-ui#9]
a this is a bit of an misnomer in the db currently, but a platform can either accept answers & ratings, only answers or only ratings. But setting this up is currently not possible. (currently not in spec...if i remember correctly)

**Comment by kelunik** [comment]
Neither in `spec` nor `object-service` nor here.

**Comment by marcelhollerbach** [comment]
for the os its just inserting the correct record into the db, not a big deal. Can you add it to the spec?

**Comment by LeanderK** [comment]
it is in the os

**Comment by kelunik** [comment]
Done via 1db65e7d15c702dce678bf6c261e77712b554c18.
